version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./work:/usr/src/app # ローカルをコンテナ内にマウント
    command: /bin/sh -c "while sleep 1000; do :; done"
